#!/usr/bin/env python
# TODO: This should probably be extracted because we use this elsewhere

subreddits = {
        'ARI': '/r/azcardinals',
        'ATL': '/r/falcons',
        'BAL': '/r/ravens',
        'BUF': '/r/buffalobills',
        'CAR': '/r/panthers',
        'CHI': '/r/chibears',
        'CIN': '/r/bengals',
        'CLE': '/r/browns',
        'DAL': '/r/cowboys',
        'DEN': '/r/denverbroncos',
        'DET': '/r/detroitlions',
        'GB':  '/r/greenbaypackers',
        'HOU': '/r/texans',
        'IND': '/r/colts',
        'JAX': '/r/jaguars',
        'KC':  '/r/kansascitychiefs',
        'MIA': '/r/miamidolphins',
        'MIN': '/r/minnesotavikings',
        'NE':  '/r/patriots',
        'NO':  '/r/saints',
        'NYG': '/r/nygiants',
        'NYJ': '/r/nyjets',
        'OAK': '/r/oaklandraiders',
        'PHI': '/r/eagles',
        'PIT': '/r/steelers',
        'LAC': '/r/chargers',
        'SF':  '/r/49ers',
        'SEA': '/r/seahawks',
        'LA': '/r/losangelesrams',
        'TB':  '/r/buccaneers',
        'TEN': '/r/tennesseetitans',
        'WAS': '/r/redskins',

        'AFC': '/AFC',
        'NFC': '/NFC',
        'APR': '/AFC',
        'NPR': '/NFC',
        }
fullnames = {
        'ARI': 'Arizona Cardinals',
        'ATL': 'Atlanta Falcons',
        'BAL': 'Baltimore Ravens',
        'BUF': 'Buffalo Bills',
        'CAR': 'Carolina Panthers',
        'CHI': 'Chicago Bears',
        'CIN': 'Cincinnati Bengals',
        'CLE': 'Cleveland Browns',
        'DAL': 'Dallas Cowboys',
        'DEN': 'Denver Broncos',
        'DET': 'Detroit Lions',
        'GB': 'Green Bay Packers',
        'HOU': 'Houston Texans',
        'IND': 'Indianapolis Colts',
        'JAX': 'Jacksonville Jaguars',
        'KC': 'Kansas City Chiefs',
        'MIA': 'Miami Dolphins',
        'MIN': 'Minnesota Vikings',
        'NE': 'New England Patriots',
        'NO': 'New Orleans Saints',
        'NYG': 'New York Giants',
        'NYJ': 'New York Jets',
        'OAK': 'Oakland Raiders',
        'PHI': 'Philadelphia Eagles',
        'PIT': 'Pittsburgh Steelers',
        'LAC': 'Los Angeles Chargers',
        'SF': 'San Francisco 49ers',
        'SEA': 'Seattle Seahawks',
        'LA': 'Los Angeles Rams',
        'TB': 'Tampa Bay Buccaneers',
        'TEN': 'Tennessee Titans',
        'WAS': 'Washington Redskins',

        'AFC': 'AFC Pro Bowl Team',
        'NFC': 'NFC Pro Bowl Team',
        'APR': 'AFC Pro Bowl Team',
        'NPR': 'NFC Pro Bowl Team',
        }
cities = {
        'ARI': 'Arizona',
        'ATL': 'Atlanta',
        'BAL': 'Baltimore',
        'BUF': 'Buffalo',
        'CAR': 'Carolina',
        'CHI': 'Chicago',
        'CIN': 'Cincinnati',
        'CLE': 'Cleveland',
        'DAL': 'Dallas',
        'DEN': 'Denver',
        'DET': 'Detroit',
        'GB': 'Green Bay',
        'HOU': 'Houston',
        'IND': 'Indianapolis',
        'JAX': 'Jacksonville',
        'KC': 'Kansas City',
        'MIA': 'Miami',
        'MIN': 'Minnesota',
        'NE': 'New England',
        'NO': 'New Orleans',
        'NYG': 'New York',
        'NYJ': 'New York',
        'OAK': 'Oakland',
        'PHI': 'Philadelphia',
        'PIT': 'Pittsburgh',
        'LAC': 'Los Angeles',
        'SF': 'San Francisco',
        'SEA': 'Seattle',
        'LA': 'Los Angeles',
        'TB': 'Tampa Bay',
        'TEN': 'Tennessee',
        'WAS': 'Washington',
        'AFC': 'AFC',
        'NFC': 'NFC',
        'APR': 'AFC',
        'NPR': 'NFC',
        }
mascots = {
        'ARI': 'Cardinals',
        'ATL': 'Falcons',
        'BAL': 'Ravens',
        'BUF': 'Bills',
        'CAR': 'Panthers',
        'CHI': 'Bears',
        'CIN': 'Bengals',
        'CLE': 'Browns',
        'DAL': 'Cowboys',
        'DEN': 'Broncos',
        'DET': 'Lions',
        'GB': 'Packers',
        'HOU': 'Texans',
        'IND': 'Colts',
        'JAX': 'Jaguars',
        'KC': 'Chiefs',
        'MIA': 'Dolphins',
        'MIN': 'Vikings',
        'NE': 'Patriots',
        'NO': 'Saints',
        'NYG': 'Giants',
        'NYJ': 'Jets',
        'OAK': 'Raiders',
        'PHI': 'Eagles',
        'PIT': 'Steelers',
        'LAC': 'Chargers',
        'SF': '49ers',
        'SEA': 'Seahawks',
        'LA': 'Rams',
        'TB': 'Buccaneers',
        'TEN': 'Titans',
        'WAS': 'Redskins',
        'AFC': 'AFC',
        'NFC': 'NFC',
        'APR': 'AFC',
        'NPR': 'NFC',
        }

twitter = {
        'ARI': 'AZCardinals',
        'ATL': 'AtlantaFalcons',
        'BAL': 'Ravens',
        'BUF': 'buffalobills',
        'CAR': 'Panthers',
        'CHI': 'ChicagoBears',
        'CIN': 'Bengals',
        'CLE': 'Browns',
        'DAL': 'dallascowboys',
        'DEN': 'Broncos',
        'DET': 'Lions',
        'GB': 'packers',
        'HOU': 'HoustonTexans',
        'IND': 'Colts',
        'JAX': 'Jaguars',
        'KC': 'chiefs',
        'MIA': 'MiamiDolphins',
        'MIN': 'Vikings',
        'NE': 'Patriots',
        'NO': 'Saints',
        'NYG': 'Giants',
        'NYJ': 'nyjets',
        'OAK': 'RAIDERS',
        'PHI': 'Eagles',
        'PIT': 'steelers',
        'LAC': 'Chargers',
        'SF': '49ers',
        'SEA': 'Seahawks',
        'LA': 'RamsNFL',
        'TB': 'TBBuccaneers',
        'TEN': 'Titans',
        'WAS': 'Redskins',
        'AFC': '',
        'NFC': '',
        'APR': '',
        'NPR': '',
        }

colors = {
 'ARI': {'all': [('Cardinal Red', '#97233F'),
                  ('White', '#FFFFFF'),
                  ('Black', '#000000'),
                  ('Yellow', '#FFB612')]
         },
 'ATL': {'all': [(u'Black', u'#000000'),
                 (u'Red', u'#A71930'),
                 (u'Silver', u'#A5ACAF'),
                 (u'White', u'#FFFFFF')],
         },
 'BAL': {'all': [(u'Purple', u'#241773'),
                 (u'Black', u'#000000'),
                 (u'Metallic Gold', u'#9E7C0C'),
                 (u'White', u'#FFFFFF')],
         },
 'BUF': {'all': [(u'Royal Blue', u'#00338D'),
                 (u'Red', u'#C60C30'),
                 (u'White', u'#FFFFFF')],
         },
 'CAR': {'all': [(u'Panther Blue', u'#0085CA'),
                 (u'Black', u'#000000'),
                 (u'Silver', u'#BFC0BF'),
                 (u'White', u'#FFFFFF')],
         },
 'CHI': {'all': [(u'Dark Navy', u'#0B162A'),
                 (u'Orange', u'#C83803'),
                 (u'White ', u'#FFFFFF')],
         },
 'CIN': {'all': [(u'Black', u'#000000'),
                 (u'Orange', u'#FB4F14'),
                 (u'White', u'#FFFFFF')],
         
         },
 'CLE': {'all': [(u'Orange', u'#FF3C00'),
                 (u'brown', u'#311D00'),
                 (u'white ', u'#FFFFFF')],
         
         },
 'DAL': {'all': [(u'Navy Blue', u'#002244'),
                 (u'Silver', u'#B0B7BC'),
                 (u'White', u'#FFFFFF'),
                 (u'Royal Blue', u'#00338D'),
                 (u'Black ', u'#000000')],
         
         },
 'DEN': {'all': [(u'Orange', u'#FB4F14'),
                 (u'Navy Blue', u'#002244'),
                 (u'White ', u'#FFFFFF')],
         
         },
 'DET': {'all': [(u'Honolulu Blue', u'#005A8B'),
                 (u'Silver', u'#B0B7BC'),
                 (u'Black', u'#000000'),
                 (u'White', u'#FFFFFF')],
         
         },
 'GB': {'all': [(u'Dark Green', u'#203731'),
                (u'Gold', u'#FFB612'),
                (u'White', u'#FFFFFF')],
        
        },
 'HOU': {'all': [(u'Deep Steel Blue', u'#03202F'),
                 (u'Battle Red', u'#A71930'),
                 (u'Liberty White', u'#FFFFFF')],
         
         },
 'IND': {'all': [(u'Royal Blue', u'#002C5F'), (u'White', u'#FFFFFF')],
         
         },
 'JAX': {'all': [(u'Black', u'#000000'),
                 (u'Teal', u'#006778'),
                 (u'Gold', u'#9F792C'),
                 (u'White', u'#FFFFFF')],
         
         },
 'KC': {'all': [(u'Red', u'#E31837'),
                (u'Gold', u'#FFB612'),
                (u'White', u'#FFFFFF')],
        
        },
 'MIA': {'all': [(u'Aqua', u'#008E97'),
                 (u'Orange', u'#F58220'),
                 (u'White', u'#FFFFFF'),
                 (u'Blue', u'#005778')],
         
         },
 'MIN': {'all': [(u'Purple', u'#4F2683'),
                 (u'Gold', u'#FFC62F'),
                 (u'White', u'#FFFFFF')],
         
         },
 'NE': {'all': [(u'Navy Blue', u'#002244'),
                (u'Red', u'#C60C30'),
                (u'Silver', u'#B0B7BC'),
                (u'White ', u'#FFFFFF')],
        
        },
 'NO': {'all': [(u'Black', u'#000000'),
                (u'Old Gold', u'#9F8958'),
                (u'White', u'#FFFFFF')],
        
        },
 'NYG': {'all': [(u'Dark Blue', u'#0B2265'),
                 (u'Red', u'#A71930'),
                 (u'White', u'#FFFFFF'),
                 (u'Gray', u'#A5ACAF')],
         
         },
 'NYJ': {'all': [(u'Green', u'#203731'), (u'White', u'#FFFFFF')],
         
         },
 'OAK': {'all': [(u'Silver', u'#A5ACAF'), (u'Black', u'#000000')],
         
         },
 'PHI': {'all': [(u'Midnight Green', u'#004953'),
                 (u'Silver', u'#A5ACAF'),
                 (u'Black', u'#000000'),
                 (u'White', u'#FFFFFF')],
         
         },
 'PIT': {'all': [(u'Black', u'#000000'),
                 (u'Gold', u'#FFB612'),
                 (u'White', u'#FFFFFF')],
         
         },
 'LAC': {'all': [(u'Navy Blue', u'#002244'),
                (u'Powder Blue', u'#0073CF'),
                (u'White', u'#FFFFFF'),
                (u'Gold', u'#FFB612')],
        
        },
 'SEA': {'all': [(u'College Navy', u'#002244'),
                 (u'Action Green', u'#69BE28'),
                 (u'Wolf Grey', u'#A5ACAF')],
         
         },
 'SF': {'all': [(u'Red', u'#AA0000'),
                (u'Gold', u'#B3995D'),
                (u'White', u'#FFFFFF'),
                (u'Black', u'#000000')],
        
        },
 'LA': {'all': [(u'Millennium Blue', u'#002244'),
                 (u'New Century Gold', u'#B3995D'),
                 (u'White', u'#FFFFFF')],
         
         },
 'TB': {'all': [(u'Buccaneer Red', u'#D50A0A'),
                (u'Pewter', u'#34302B'),
                (u'Black', u'#000000'),
                (u'Orange', u'#FF7900'),
                (u'White ', u'#FFFFFF')],
        
        },
 'TEN': {'all': [(u'Navy', u'#002244'),
                 (u'Titans Blue', u'#4B92DB'),
                 (u'Red', u'#C60C30'),
                 (u'White', u'#FFFFFF'),
                 (u'Silver', u'#85888B')],
         
         },
 'WAS': {'all': [(u'Burgundy', u'#773141'),
                 (u'Gold', u'#FFB612'),
                 (u'White', u'#FFFFFF')],
         
         },
 'AFC': {'all': [(u'Red', u'#DB1F26'),
                 (u'White', u'#FFFFFF')],
         },
 'NFC': {'all': [(u'Blue', u'#12376E'),
                 (u'White', u'#FFFFFF')],
         },
 'APR': {'all': [(u'Red', u'#DB1F26'),
                 (u'White', u'#FFFFFF')],
         },
 'NPR': {'all': [(u'Blue', u'#12376E'),
                 (u'White', u'#FFFFFF')],
         },
 }


for short in colors:
    colors[short]['bg'] = colors[short]['all'][0]
    colors[short]['fg'] = colors[short]['all'][1]
    if short == 'BAL':
        colors[short]['fg'] = colors[short]['all'][2]

fullinfo = {}
for team in list(mascots.keys()):
    fullinfo[team] = {
            'short': team,
            'mascot': mascots[team],
            'fullname': fullnames[team],
            'city': cities[team],
            'subreddit': subreddits[team],
            'twitter': twitter[team],
            }

def fix_team(team):
    replacements = {
            'JAC': 'JAX',
            'SD': 'LAC',
            'STL': 'LA',
            'LAR': 'LA',
            'ARZ':'ARI',
            'CLV':'CLE',
            'HST':'HOU',
            'SL' :'LA',
            }
    if team in replacements:
        return replacements[team]
    return team

def get_team(team):
    team = fix_team(team)
    if team in fullinfo:
        return fullinfo[team]

if __name__ == '__main__':
    for short, info in fullinfo.items():
        print("{short:3}  {city:15}  {mascot}".format(**info))
